### PR TITLE
Add support for custom dump locations

### PR DESCRIPTION
**Pull request by tunip3**
This is done with a new -d argument for directory to dump to:
-d {folder}

### CODE REVIEW

**Comment by Wunkolo** [comment]
Can you please separate the Logging-argument changes into a separate PR from this custom output folder one? This PR makes no indication of adding this feature and I'd like to review that separately and keep these feature PRs atomic.

**Comment by tunip3** [comment]
done #40

**Comment by Wunkolo** [comment]
Gonna wanna rebase this one to master now so there aren't any conflicts

**Comment by tunip3** [comment]
moved to #41

**Pull request closed without merging**
